##
# ArgoCD values
##

## Helm Repo GIT
helmRepoUrl: https://github.com/mid998/mcgstandalone

# ArgoCD apps definition
apps:
  deploy-mcg:
    branch: main
    enabled: true
    path: mcg/
    autosync: true

namespaces:
  - openshift-storage
  - openshift-operators
  - openshift-gitops
